
export const localimag={
    email:require('../Icons/email.png'),
    password:require('../Icons/password.png'),
    splash:require('../Icons/new_logo.png'),
    back:require('../Icons/back.png'),
    user:require('../Icons/user.png'),
    notification:require('../Icons/notification.png'),
    resetpassword:require('../Icons/resetpassword.png'),
    terms:require('../Icons/terms.png'),
    privacy:require('../Icons/privacy.png'),
    about:require('../Icons/about.png'),
    contact:require('../Icons/contact.png'),
    rate:require('../Icons/rate.png'),
    shareapp:require('../Icons/shareapp.png'),
    logout:require('../Icons/logout.png'),
    userplaceholder:require('../Icons/userplaceholder.png'),
    dots:require('../Icons/dots.png'),
    camera:require('../Icons/camera.png'),
    share:require('../Icons/share.png'),
    pen:require('../Icons/pen.png'),
    no_data:require('../Icons/no_data.png'),
    cancel:require('../Icons/cancel.png'),
    down:require('../Icons/down.png'),
    up_arrow:require('../Icons/up_arrow.png'),

    HomeHeader:require('../Icons/Rectangle_90.png'),
    RupeyBag:require('../Icons/Screenshot_1.png'),
    Home:require('../Icons/Screenshot_2.png'),
    User:require('../Icons/Screenshot_5.png'),
    Enquiry:require('../Icons/Screenshot_4.png'),
    Dues:require('../Icons/Screenshot_3.png'),
}